version: '3.9'
services:
  httpstub:
    image: rust:1.75
    working_dir: "/app"
    command:
      - sh
      - -c
      - "cargo build --release --package stubs && /app/target/release/stubs -p 8181 /stubs"
    volumes:
      - ".:/app"
      - "./downloader/tests/http-stubs:/stubs"
    ports:
      - "8181:8181"