version: '3.9'
services:
  httpstub:
    build:
        context: .
        dockerfile: ./downloader/tests/http-stubs/Dockerfile
    working_dir: "/stubs"
    command:
      - gostub -p 8181
    volumes:
      - "./downloader/tests/http-stubs:/stubs"
    ports:
      - "8181:8181"