[package]
name = "downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json", "blocking"] }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
domain = { path = "../domain" }
chrono = "0.4.38"
